openapi: 3.0.0
info:
  title: AGRIHUB API
  version: 1.0.0
security:
  - sessionAuth: []
paths:
  /healthcheck:
    get:
      tags:
        - Healthcheck
      description: Responds if the app is up and running
      responses:
        "200":
          description: App is up and running
  #authentication paths
  /api/auth/login:
    post:
      tags:
        - Auth
      summary: authenticate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginSchema"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAuthResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"
  /api/auth/me:
    get:
      tags:
        - Auth
      summary: get current user from session
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSchema"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"
  /api/account/signup:
    post:
      tags:
        - Account
      summary: Register a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegisterSchema"
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      message:
                        type: string
        "400":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"
  /api/account/send-verification:
    post:
      tags:
        - Account
      summary: Register a user
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"
  /api/account/verify-email/{id}:
    get:
      tags:
        - Account
      summary: verify email
      deprecated: true
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"
  /api/account/profile-completion:
    post:
      tags:
        - Account
      summary: complete user details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCompletionSchema"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAuthResponse"
        "400":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"
  /api/account/setup-profile:
    post:
      tags:
        - "Account"
      summary: "Setup username and tags"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UserProfile"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAuthResponse"
        "400":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"
  /api/user/profile/{username}:
    get:
      tags:
        - "User"
      summary: "Search User"
      parameters:
        - name: username
          in: path
          required: true
          description: Search key'
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "404":
          description: Not Found Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"
  /api/tags/search:
    get:
      tags:
        - "Tags"
      summary: "Search tags"
      parameters:
        - name: key
          in: query
          description: Search key'
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagsSchema"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"
  /api/user/profile/{id}:
    put:
      tags:
        - "User"
      summary: Update user profile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: User ID
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UserUpdateProfile"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagsSchema"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"
  /api/forums:
    get:
      tags:
        - Forums
      summary: Get Questions Data
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Search term for forums (optional)
        - in: query
          name: page
          schema:
            type: string
          description: Page number (optional)
        - in: query
          name: perpage
          schema:
            type: string
          description: Number of items per page (optional, default 10)
        - in: query
          name: filter
          schema:
            type: string
          description: Filter criteria (optional, default newest)
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuestionsResponse"
        "400":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"
    post:
      tags:
        - Forums
      description: Create Questions
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/QuestionSchema"
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewQuestionSchema"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerError"

# components
components:
  securitySchemes:
    sessionAuth:
      type: apiKey
      name: session
      in: cookie
  schemas:
    # Authentication Schemas
    UserLoginSchema:
      type: object
      required:
        - user
        - password
      properties:
        user:
          type: string
          default: daniel1234
        password:
          type: string
          default: qweR123$
    QuestionsResponse:
      type: object
      properties:
        questions:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              user:
                type: object
                properties:
                  avatar:
                    type: string # Adjust if it has a specific type
                  id:
                    type: string
                  username:
                    type: string # Adjust if it has a specific type
              tags:
                type: array
                items:
                  type: object
                  properties:
                    tag:
                      type: string
              title:
                type: string
              question:
                type: string
              imagesrc:
                type: array
                items:
                  type: string
              createdat:
                type: string
                format: date-time
              updatedat:
                type: string
                format: date-time
              answer_count:
                type: string
              vote_count:
                type: string
        pagination:
          type: object
          properties:
            page:
              type: integer
            per_page:
              type: integer
            total_pages:
              type: integer
            total_records:
              type: integer
    UserRegisterSchema:
      type: object
      required:
        - email
        - password
        - confirmPassword
      properties:
        email:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
    UserCompletionSchema:
      type: object
      required:
        - firstname
        - lastname
        - birthdate
        - present_address
        - zipcode
        - district
        - municipality
      properties:
        firstname:
          type: string
        lastname:
          type: string
        birthdate:
          type: string
        present_address:
          type: string
        zipcode:
          type: string
        district:
          type: string
        municipality:
          type: string
    UserSchema:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        birthdate:
          type: string
        present_address:
          type: string
        zipcode:
          type: string
        district:
          type: string
        municipality:
          type: string
        verification_level:
          type: string
        createdat:
          type: string
        updatedat:
          type: string
        avatar:
          type: string
    UserProfile:
      type: object
      properties:
        avatar:
          type: string
          format: binary
        username:
          type: string
        tags:
          type: array
          items:
            type: string
    UserUpdateProfile:
      type: object
      properties:
        avatar:
          type: string
          format: binary
        username:
          type: string
        email:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        birthdate:
          type: string
          format: date
        present_address:
          type: string
        zipcode:
          type: string
        district:
          type: string
        municipality:
          type: string
        verification_level:
          type: string
        bio:
          type: string
    QuestionSchema:
      type: object
      required:
        - title
        - question
        - imagesrc
      properties:
        title:
          type: string
          description: The title of the forum entry
        question:
          type: string
          description: The question in the forum entry
        imagesrc:
          type: array
          items:
            type: string
            format: binary
          description: One or more images associated with the forum
    NewQuestionSchema:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the new question
        userid:
          type: string
          description: The user ID associated with the question
        title:
          type: string
          description: The title of the new question
        question:
          type: string
          description: The content of the new question
        imagesrc:
          type: array
          items:
            type: string
          description: Array of image URLs associated with the question
        createdat:
          type: string
          format: date-time
          description: The timestamp when the question was created
        updatedat:
          type: string
          format: date-time
          description: The timestamp when the question was last updated
    TagsSchema:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          tag_name:
            type: string
    UserAuthResponse:
      type: object
      properties:
        message:
          type: string
        user:
          $ref: "#/components/schemas/UserSchema"
    ErrorResponse:
      type: object
      properties:
        error:
          type: boolean
          default: true
        message:
          type: string
        validationErrors:
          type: array
          items:
            $ref: "#/components/schemas/ZodValidationError"
    ServerError:
      type: object
      properties:
        error:
          type: boolean
          default: true
        message:
          type: string
          default: Server Error
    ZodValidationError:
      type: object
      properties:
        code:
          type: string
        expected:
          type: string
        received:
          type: string
        path:
          type: array
          items:
            type: string
        message:
          type: string
tags: []
